class PopupEngine{
	static modal = document.createElement("div")
	static modalContent = document.createElement("div")
	static inline = document.createElement("div")

	static initialized = false
	static config = {
		doLogs: true,
		modalBlur: true
	}

	static endModal 

	static init(config){
		if(this.initialized == true){
			if(this.config.doLogs)
			console.log("PopupEngine is already initialized, will ignore this call.")
			return
		}

		//configure the engine
		if(config){
			this.config = config
		}

		//create needed html
		this.modal.classList.add("popupEngineModalContainer")
		this.modal.style.display = "none"
		this.modalContent.classList.add("popupEngineModalContent")
		this.modal.appendChild(this.modalContent)

		this.inline.classList.add("popupEngineInlineContainer")
		this.inline.style.scale = 0

		if (document.readyState === 'complete' || document.readyState === 'interactive') {
			this.addDOMElems()
		} 
		else {
			window.addEventListener('load', ()=>{
				this.addDOMElems()
			});
		}
	}

	static addDOMElems(){
		document.body.appendChild(document.createComment('Code generated by popupEngine'))
		document.body.appendChild(this.modal)
		document.body.appendChild(this.inline)

		this.createCSS()

		this.initialized = true
	}

	static createCSS(){
		//create stylesheet
		const style = document.createElement('style')
		document.head.appendChild(style)

		const stylesheet = style.sheet

		//----------- modal -----------//
		//#region 
		stylesheet.insertRule(`:where(.popupEngineModalContainer){
			position: fixed;
			inset: 0;
			background-color: hsla(0,0%,0%,.3);
			z-index: 1000;
			display: none;
			place-content: center;
			font-family: sans-serif;
			color: var(--popupEngine-color);
			transition: opacity .3s;
			opacity:0;
			${this.config.modalBlur ? "backdrop-filter: blur(4px);" : ""}

			--popupEngine-background-color: white;
			--popupEngine-color: black;
		}`)

		stylesheet.insertRule(`:where(.popupEngineModalContent) { 
			background-color: var(--popupEngine-background-color);
			padding: 2vw 5vw;
			max-width: 90vw;
			min-width: 25vw;
			overflow: hidden;
			word-wrap: break-word;
			transition: scale .3s;
			transition-timing-function: cubic-bezier(.13,.68,.46,1.33);
			scale: 0; 
		}`)

		stylesheet.insertRule(`:where(.popupEngineModalHeading) {
			text-align: center;
			font-size: 1.5rem
		}`)

		stylesheet.insertRule(`:where(.popupEngineModalText) {
			text-align: center;
			margin-bottom: 1rem;
		}`)
		
		stylesheet.insertRule(`:where(.popupEngineModalInputs) {
			display: flex;
				flex-direction: column;
				justify-content: center;
		}`)
		
		stylesheet.insertRule(`:where(.popupEngineModalInput) {
			padding: .5rem;
			border: 1px solid gray;
			margin: .2rem 0 .5rem 0;
			color: var(--popupEngine-color);
		}`)
		
		stylesheet.insertRule(`:where(.popupEngineModalInputLabel) {
			font-size: .9rem;
		}`)
		
		stylesheet.insertRule(`:where(.popupEngineModalButtons) {
			display: flex;
				flex-wrap: wrap;
				gap: 1rem;
				justify-content: center;
		}`)
		
		stylesheet.insertRule(`:where(.popupEngineModalButton) {
			cursor: pointer;
			border: 1px solid gray;
			padding: .5rem;
			color: var(--popupEngine-color);
		}`)
		//#endregion
		
		//----------- inline -----------//
		//#region 

		stylesheet.insertRule(`:where(.popupEngineInlineContainer) { 
			position: absolute;
			z-index: 1000;
			display: grid;
			place-items: center;

			--popupEngine-background-color: white;
		}`)

		stylesheet.insertRule(`:where(.popupEngineInlineContent) { 
			background-color: var(--popupEngine-background-color);
			padding: .65rem;
			max-width: 30vw;
			word-wrap: break-word;
			transition: scale .3s;
			transition-timing-function: cubic-bezier(.13,.68,.46,1.33);
			box-shadow: 0 0 .3rem .3rem rgba(0,0,0,.1);
			grid-area: 1 / 1 / 2 / 2;
			transform: translateX(0);
		}`)

		stylesheet.insertRule(`:where(.popupEngineInlinePointer) { 
			content: "";
			background-color: var(--popupEngine-background-color);
			transform:  translateY(100%) rotate(45deg);
			box-shadow: 0 0 .3rem .3rem rgba(0,0,0,.1);
			aspect-ratio: 1;
			width: 1rem;
			grid-area: 1 / 1 / 2 / 2;
		}`)

		stylesheet.insertRule(`:where(.popupEngineInlineText) {
			margin: 0;
		}`)

		stylesheet.insertRule(`:where(.popupEngineInlineHeading) {
			text-align: center;
			margin-bottom: 1rem;
		}`)

		//#endregion
	}

	static createInlinePopup(settings = {}){
		if(!this.checkHTML)return

		if(!settings.position)
			settings.position = "mouse"

		if(settings.position instanceof Element){
			console.log("elem")
		}
		else if(settings.position == "mouse event so that you can use clientX"){
			console.log("mouse")
		}

		this.inline.innerHTML = ""

		let content = document.createElement('div')
		content.classList.add("popupEngineInlineContent")

		//create heading
		if(settings.heading){
			let heading = document.createElement("p")
			heading.innerHTML = settings.heading
			heading.classList.add("popupEngineInlineHeading")

			content.appendChild(heading)
		}

		//generate text
		let popupText = document.createElement("p")
		popupText.classList.add("popupEngineInlineText")
		popupText.innerHTML = settings.text || "no text specified"

		content.appendChild(popupText)

		let pointer = document.createElement('div')
		pointer.classList.add("popupEngineInlinePointer")
		this.inline.appendChild(pointer)

		this.inline.appendChild(content)

		this.inline.style.scale = 1
	}

	static createModal(settings = {}){
		return new Promise((resolve, reject) => {
			this.endModal = resolve
	
			if(!this.checkHTML)return
	
			if(this.modal.style.display != "none"){
				if(this.config.doLogs)
				console.log('overwriting old popup: "' + this.modalContent.querySelector(".popupEngineModalText").innerHTML + '"')
			}
			
			//#region generate content

			this.modalContent.innerHTML = ""

			//create heading
			if(settings.heading){
				let heading = document.createElement("p")
				heading.innerHTML = settings.heading
				heading.classList.add("popupEngineModalHeading")

				this.modalContent.appendChild(heading)
			}

			//generate text
			let popupText = document.createElement("p")
			popupText.classList.add("popupEngineModalText")
			popupText.innerHTML = settings.text || "no text specified"
	
			this.modalContent.appendChild(popupText)

			//create input
			if(!settings.inputs || settings.inputs.length == 0){
				settings.inputs = []
			}

			let popupInputs = document.createElement("div")
			popupInputs.classList.add("popupEngineModalInputs")

			for (let i = 0; i < settings.inputs.length; i++) {
				let input = document.createElement("input")

				if(settings.inputs[i].label){
					input.name = i

					let label = document.createElement("label")
					label.classList.add("popupEngineModalInputLabel")
					label.innerText = settings.inputs[i].label

					popupInputs.appendChild(label)
				}

				input.classList.add("popupEngineModalInput")
				input.type = settings.inputs[i].type || "text"
				input.placeholder = settings.inputs[i].placeholder || ""
	
				popupInputs.appendChild(input)
			}
	
			this.modalContent.appendChild(popupInputs)
			
			//create buttons
			if(!settings.buttons || settings.buttons.length == 0){
				settings.buttons = [{text: "okay"}]
			}
	
			let popupButtons = document.createElement("div")
			popupButtons.classList.add("popupEngineModalButtons")
			
			for (let i = 0; i < settings.buttons.length; i++) {
				let button = document.createElement("button")
				button.classList.add("popupEngineModalButton")
				button.innerText = settings.buttons[i].text
				button.onclick = function () { 
					PopupEngine.closeModal(
						settings.buttons[i].closePopup, 
						settings.buttons[i].action, 
						{
							text: settings.text,
							heading: settings.heading,
							buttons: settings.buttons,
							inputs: settings.inputs,
							buttonIndex: i,
						}
				)}
	
				popupButtons.appendChild(button)
			}
	
			this.modalContent.appendChild(popupButtons)
	
			//#endregion
	
			//show popup
			this.modal.style.display = "grid"
			setTimeout(function(){
				document.querySelector('.popupEngineModalContainer').style.opacity = 1
				document.querySelector('.popupEngineModalContent').style.scale = 1
			},0)
		})
	}

	static closeModal(closePopup = true, closeAction, data){
		//get values of inputs
		if(this.modalContent.querySelector(".popupEngineModalInputs")){
			let inputValues = []
			document.querySelectorAll('.popupEngineModalInputs .popupEngineModalInput').forEach(item => {
				inputValues.push(item.value)
			})
			data.inputValues = inputValues
		}

		if(closeAction){
			closeAction(data)
		}

		if(closePopup){
			this.modal.style.display = "none"
			this.modal.style.opacity = 0
			this.modalContent.style.scale = 0

			this.endModal(data)
		}
	}

	static checkHTML(){
		if (document.readyState === 'loading') {
			if(this.config.doLogs)
			console.error("PopupEngine cant be run before DOM content has finished loading. Try adding a window.load() event arround this call or use defer.")
			return false
		} 

		if(!this.initialized){
			if(this.config.doLogs)
			console.error("PopupEngine has not yet been initialized: PopupEngine.init(). \n try running PopupEngine.test()")
			return false
		}
	}

	/**
	 * test method, creates one popup and outputs errors
	 */
	static test(){
		if(!this.initialized){
			console.error("TEST: PopupEngine has not yet been initialized: PopupEngine.init()")
			return
		}
		if(!document.querySelector('.popupEngineModalContainer')){
			console.error("TEST: Could not find DOM elements needed to run PopupEngine. This is probably because the Engine has not yet been initialized: PopupEngine.init()")
			return
		}
		if(!document.querySelector('.popupEngineModalContent')){
			console.error("TEST: Could not find DOM elements needed to run PopupEngine. This might be a problem with the initialization but is probably because another script has changed the engines elements or because your version of the engine is faulty.")
			return
		}
		console.log("TEST: all DOM elements seem fine");
		console.log(
		`TEST: Generating a test popup`);
		PopupEngine.createModal({
			heading: "test",
			text: "this is a test",
			buttons: [
				{
					text: "okay",
					action: (data) => {console.log("buttonpressed, value:", data.inputValues[0])}
				}
			],
			inputs: [
				{
					type: "text",
				}
			]
		})
	}
}